spring:
  application:
    name: kafka-project-template


communication-channel:
  kafka:
    # You can split to Producer/Consumer configuration depend on your needs
    topic: course.tracking.progress
    bootstrap-servers: localhost:9092
    client-id: application
    retry-backoff-ms: 1000
    request-timeout-ms: 30000
    # Publisher Configuration
    compression-type: lz4  # gzip, snappy, lz4, zstd
    acks: all
    retries: 2000
    max-request-size: 1049600
    reconnect-backoff-ms: 50
    batch-size: 16384
    buffer-memory: 33554432
    linger-ms: 5

logging:
  level:
    dev.tpcoder.contentdelivery: DEBUG